name: Api

on:
  push:
    branches:
    - master
    - /*
#    paths:
#    - 'Xpirit.BeerXchange/**'

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - name: checkout repo
      uses: actions/checkout@v1
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108

    - name: Install hub
      uses: geertvdc/setup-hub@master
      
    - name: Build & Release
      env:
        GITHUB_USER: ${{ secrets.GITHUB_USER }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
           version=$(hub release | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{$NF=sprintf("%0*d", length($NF), ($NF+1)); print}')
           echo $version
           dotnet publish --configuration Release --output ../artifacts/api
           pwd        
           zip -r api-$version.zip artifacts/api
           hub release create -m $version -a api-$version.zip $version
      
#     - name: Create a Release
#       uses: elgohr/Github-Release-Action@master
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         args: MyReleaseMessage
